# Generated by Django 5.0.7 on 2024-07-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BayesResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, verbose_name='创建时间')),
                ('modified', models.DateTimeField(editable=False, verbose_name='修改时间')),
                ('vocab', models.TextField(verbose_name='词汇表')),
                ('p1V', models.TextField(verbose_name='p1V')),
                ('p0V', models.TextField(verbose_name='p0V')),
                ('PAb', models.FloatField(verbose_name='P(A|B)')),
            ],
            options={
                'verbose_name': '贝叶斯情感分析',
                'verbose_name_plural': '贝叶斯情感分析',
            },
        ),
    ]
